// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDewrF7CWDOS3a3jpj4FwsKT5ymPR_YyDE',
    appId: '1:120636488876:web:17eb7c092c570f12e57309',
    messagingSenderId: '120636488876',
    projectId: 'lab2-project-213086-4bc33',
    authDomain: 'lab2-project-213086-4bc33.firebaseapp.com',
    storageBucket: 'lab2-project-213086-4bc33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBljbj7kdXA0gCICvE0S8cnkl7Y7nOJvI',
    appId: '1:120636488876:android:05682050e4d25385e57309',
    messagingSenderId: '120636488876',
    projectId: 'lab2-project-213086-4bc33',
    storageBucket: 'lab2-project-213086-4bc33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcXYba4Yq8z7Nnq-RBxRNaC50st9glRk',
    appId: '1:120636488876:ios:3610c76582854b50e57309',
    messagingSenderId: '120636488876',
    projectId: 'lab2-project-213086-4bc33',
    storageBucket: 'lab2-project-213086-4bc33.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIcXYba4Yq8z7Nnq-RBxRNaC50st9glRk',
    appId: '1:120636488876:ios:3610c76582854b50e57309',
    messagingSenderId: '120636488876',
    projectId: 'lab2-project-213086-4bc33',
    storageBucket: 'lab2-project-213086-4bc33.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDewrF7CWDOS3a3jpj4FwsKT5ymPR_YyDE',
    appId: '1:120636488876:web:2e555e6096566ebee57309',
    messagingSenderId: '120636488876',
    projectId: 'lab2-project-213086-4bc33',
    authDomain: 'lab2-project-213086-4bc33.firebaseapp.com',
    storageBucket: 'lab2-project-213086-4bc33.firebasestorage.app',
  );
}
